name: Deploy Docker Images para Docker Hub

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem do backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gestao-backend ./gestao_api_backend

      - name: Push da imagem do backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gestao-backend

      - name: Build da imagem do frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gestao-frontend ./gestao_api

      - name: Push da imagem do frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gestao-frontend
