# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend dependencies
        working-directory: gestao_financeira/gestao_api
        run: npm ci

      - name: Build frontend
        working-directory: gestao_financeira/gestao_api
        run: npm run build

      - name: Install backend dependencies
        working-directory: gestao_financeira/gestao_api/gestao_api_backend
        run: npm ci

      - name: Run backend tests
        working-directory: gestao_financeira/gestao_api/gestao_api_backend
        run: npm test
